### ISSUE TITLE
Remove Column Highlights

### ISSUE THREAD

**Issue by alifr** [BtheGit/sortable-js#2]
Column highlighting is a terrible idea. It's makes it difficult to scan table rows for information. Ask any IA who knows their stuff. At least make it configurable and FALSE by default.

**Comment by alifr** [comment]
+1

**Comment by mltnewman** [comment]
+1

**Comment by BtheGit** [comment]
Well, it's only a hook for the CSS. It's on you if you actually style it as such. ;)
